### ISSUE TITLE
Cannot alter type of a column used by a view or rule

### ISSUE THREAD

**Issue by ramzes13** [abelosorio/sequelize_replace_enum_postgres#10]
Hello,
I have a table and view based on that table.
During migration I get this error:
`ERROR: cannot alter type of a column used by a view or rule`

Thanks

**Comment by abelosorio** [comment]
Hi @ramzes13! This error is because you have entities that depend on the table you're trying to migrate.

I'll close this issue since it's not an issue of the migration tool.

I'd suggest using the `\d+ <YOUR_TABLE>` command to check your table's dependencies.

Good luck!

**Comment by ramzes13** [comment]
I drop the views, alter the column type on the underlying table, and then recreate the views.
