### ISSUE TITLE
Harmonize args names

### ISSUE THREAD

**Issue by cyrilchapon** [abelosorio/sequelize_replace_enum_postgres#11]
I'm not using the `default` function but rather the `addEnum` and `dropEnum` ones.

- `addEnum` expects `name`
- `dropEnum` expects `enumName`
- other functions expects every time different arg names.

I'm going to PR it.

NB: related to https://github.com/abelosorio/sequelize_replace_enum_postgres/issues/7

**Comment by abelosorio** [comment]
Nice!

**Comment by abelosorio** [comment]
Released into https://www.npmjs.com/package/sequelize-replace-enum-postgres/v/1.6.0.
