### ISSUE TITLE
Pass down transaction

### ISSUE THREAD

**Issue by cyrilchapon** [abelosorio/sequelize_replace_enum_postgres#12]
The strategy taken in "unitary" function (`dropEnum` for example) to accept a passed down `transaction` (and even `sequelizeOptions` more generaly) should be replicated to the main function.

Why ?

For example, in here we're managing some migrations inside a whole transaction, because that make sense to create, for example, an enum + a table + some index in a single migration. We want it to success-all or fail-all, thus we wrap it inside a transaction

For example, in the up :
```
    return sqlQueryInterface.sequelize.transaction(t => {
      return createEnum({
        // ... Omitted for example
        name: 'my_enum_type',
        sequelizeOptions: { transaction: t }
      })
        .then(() => {
          return sqlQueryInterface.createTable('my_table', {
            // ... Omitted for example
            myEnumColumn: {
              field: 'my_enum_column',
              type: 'my_enum_type',
              allowNull: false
            },
          }, {
            transaction: t
          })
            .then(() => {
              return Promise.all([
                sqlQueryInterface.addIndex('my_index', {
                  // ... omitted for example
                  transaction: t
                }),
                sqlQueryInterface.addIndex('my_second_index', {
                  // ... Omitted for example
                  transaction: t
                })
              ])
            })
        })
    })
```

Notice how we pass-down `sequelizeOptions` with `transaction` to `createEnum`

This is currently impossible with `default` function (`changeEnum`).

I'm going to PR it

**Comment by GochoMugo** [comment]
If you have come across this issue and need
a quick work-around **that you should probably not use**:

```ts
const queryInterface = getQueryInterfaceSomehow();
const transaction = getTransactionSomehow();

await replaceEnum({
  // ...
  queryInterface: {
    sequelize: {
      query: queryInterface.sequelize.query.bind(queryInterface.sequelize),
      transaction: (fn: (t: Sequelize.Transaction) => Promise<any>) => {
        return fn(transaction);
      },
    },
  },
});
```

**Comment by abelosorio** [comment]
Thanks for your contribution @cyrilchapon, and sorry for the super late response. I haven't had any time to allocate to this project.

Thanks again
