### ISSUE TITLE
Invalid input value for enum

### ISSUE THREAD

**Issue by gorango** [abelosorio/sequelize_replace_enum_postgres#14]
Using the following setup:
```javascript
up: async (queryInterface) => {
  return replaceEnum({
    queryInterface,
    tableName: 'transfers',
    columnName: 'type',
    newValues: ['payment', 'payout'],
    enumName: 'enum_transfers_type'
  })
},
down: async (queryInterface) => {
  return replaceEnum({
    queryInterface,
    tableName: 'transfers',
    columnName: 'type',
    newValues: ['deposit', 'withdraw'],
    enumName: 'enum_transfers_type'
  })
}
```

Receiving the following error:
ERROR: invalid input value for enum `enumName`: `newValues[0]`

Possibly related to #5

**Comment by abelosorio** [comment]
Hi @gorango, I'm out of work this week, but I'll check this to this as soon as I get back.

**Comment by cyrilchapon** [comment]
@gorango this is related for rows already inside the table with old values.
I think you should provide a `defaultValue` for them, but I'm not that sure it works.

**Comment by abelosorio** [comment]
Yes @gorango, effectively you need to pass down a default value.

**Comment by gorango** [comment]
Can confirm - this solves the issue.
