### ISSUE TITLE
Error: Invalid input value for enum

### ISSUE THREAD

**Issue by markjackson02** [abelosorio/sequelize_replace_enum_postgres#16]
When I try to run this during migration:

```
replaceEnum({
            queryInterface,
            tableName: 'mytable',
            columnName: 'mycolumn',
            defaultValue: null,
            newValues: ['My Enum Value'],
            enumName: 'enum_mytable_mycolumn',
          });
```

I get this error: 
```
Unhandled rejection SequelizeDatabaseError: invalid input value for enum "enum_mytable_mycolumn_new": "{"Some Existing Enum Value"}"
    at Query.formatError (C:\myProject\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at C:\myProject\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (C:\myProject\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\myProject\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\myProject\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\myProject\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\myProject\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\myProject\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\myProject\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\myProject\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\myProject\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

My full migration looks like this:
```
up: (queryInterface, Sequelize) => {
      return new Promise(async (resolve, reject) => {
        try {
          await replaceEnum({
            queryInterface,
            tableName: 'mytable',
            columnName: 'mycolumn',
            defaultValue: null,
            newValues: ['My Enum Value'],
            enumName: 'enum_mytable_mycolumn',
          });
          resolve();
        } catch (err) {
          console.log(err);
          reject();
        }
    });
  },
```

Any ideas what could be happening here?

I am running:

- Node 12.13.0
- "sequelize": "^5.21.1",
    "sequelize-cli": "^5.5.1",
    "sequelize-replace-enum-postgres": "^1.5.0",
   "pg": "^7.12.1",

Thanks

**Comment by Julyyq** [comment]
+1

**Comment by markjackson02** [comment]
I get the same error when I do that. In any case, newValues should _replace_ oldValues. In your suggestion, `down` method would never work if you could only add new values, not replace/delete existing ones.

**Comment by abelosorio** [comment]
Hi @markjackson02, you're setting new values with spaces, which I don't know is not allowed in PostgreSQL:
```javascript
newValues: ['My Enum Value'],
```
And also I don't think it's a good practice.

Can you confirm this?

**Comment by markjackson02** [comment]
Thanks for your reply.

Spaces are supported in postgres. Documentation states "White space in the labels is significant" and they use value = `very happy` as an example:
https://www.postgresql.org/docs/10/datatype-enum.html

However it is not white spaces that is causing this error. I tested existing & new enums without white spaces and I get the same error.

**Comment by zcuric** [comment]
I have the exact same issue.

**Comment by markjackson02** [comment]
To get around this I've moved away from using enums that I expect to ever change, and just do the string validation in my ORM. This would be nice to have though.

**Comment by GochoMugo** [comment]
This errors occurs when you are trying to add/replace an enum when
some records contain a value in the affected table column that does
**not** match any of the (new) enum variants.

For example, you might have an enum with variants
`["rectangle", "square", "triangle"]`. A row in the table has the
column value `"triangle"`. If you attempt to replace the enum with
`["rectangle", "square"]` i.e. remove variant `"triangle"`, you'll
get an error `invalid input value for enum`.

Possible solutions include:
- drop the offending rows; a soft delete will not work.
- update the column values to some other value e.g. (using our example above)
  set all `"triangle"` shapes to become `"square"`; depends on your use case.
