### ISSUE TITLE
Enum arrays

### ISSUE THREAD

**Issue by bhumbash** [abelosorio/sequelize_replace_enum_postgres#20]
When I use this package to alter the enum, it works perfectly. However, my data type is an array of enums - Sequelize.ARRAY(Sequelize.ENUM(1,2,3)). After I run the replaceEnum function, the data type is just set to being an enum, not an array of enums. Is there any way around this?

**Comment by abelosorio** [comment]
Hi, @bhumbash. There is no workaround I can think of.

Moreover, having an array of enumerated values is having multiple values in a column, which violates the first normal form: https://en.wikipedia.org/wiki/First_normal_form.

Hope it helps.
