### ISSUE TITLE
Why don't you await replaceEnum?

### ISSUE THREAD

**Issue by GorgeousPuree** [abelosorio/sequelize_replace_enum_postgres#22]
Hello, thanks for your package. I'm suffering with updating my enum all day and finally found your package.
So your code is based on promises, and my question is why don't you **await** for a promise in your example? Why doesn't example look like this? Thanks a lot.
```
module.exports = {
  up: async (queryInterface, Sequelize) => {
    return await replaceEnum({
      queryInterface,
      tableName: 'eventRecurrence',
      columnName: 'recurrenceType',
      defaultValue: 'weekly',
      newValues: ['weekly', 'monthly', 'yearly', 'on-demand'],
      enumName: 'enum_event_recurrence_recurrence_type'
    });
  },
```

**Comment by abelosorio** [comment]
Hi, @GorgeousPuree! I'm glad this package helps you.

Sequelize's migrations expect a Promise to be returned from the up/down functions. That's why `replaceEnum` returns the Promise directly without waiting for it to resolve.

I hope that helps.

**Comment by GorgeousPuree** [comment]
@abelosorio, oh I see. Thanks you for your answer and clarification!
