### ISSUE TITLE
Rename Enum

### ISSUE THREAD

**Issue by RickEyre** [abelosorio/sequelize_replace_enum_postgres#25]
Is it possible to rename the enum with this library?

**Comment by abelosorio** [comment]
Hey @RickEyre. Yes, that's exactly what this does.

**Comment by RickEyre** [comment]
Sorry, but I don't see an argument for the new name of the enum.

I want to change the current enum name, to an entirely different name.

For example, enum_first_name to enum_second_name.

**Comment by RickEyre** [comment]
Awesome, thank you so much for your answer!
