### ISSUE TITLE
Default value required?

### ISSUE THREAD

**Issue by PorterK** [abelosorio/sequelize_replace_enum_postgres#5]
Why is default value required? Should be an optional value in the same way that Sequelize doesn't enforce a default value.

If you don't provide a default you get

```sh
ERROR: invalid input value for enum "enum": "undefined"
```

Thanks

**Comment by abelosorio** [comment]
Hi @PorterK thanks for your contribution. Yes, the default value should be optional.

Feel free if you want to submit a PR with this change. Otherwise I'll adjust it and publish a new version of the package later today.

Thanks!

**Comment by abelosorio** [comment]
@PorterK I made the changes :point_up: 

Please let me know if that works for you.

Greetings!

**Comment by PorterK** [comment]
Thank you @abelosorio!
