### ISSUE TITLE
Use Postgres' ALTER TYPE when the operation only requires to add new values

### ISSUE THREAD

**Issue by abelosorio** [abelosorio/sequelize_replace_enum_postgres#9]
Since PostgreSQL supports adding new values by using ALTER TYPE (https://www.postgresql.org/docs/current/static/sql-altertype.html) I think it's easier to use it when the migration only requires to add new values.

Removing values from enum is still unsupported :/

See https://github.com/sequelize/sequelize/issues/7151#issuecomment-414698500

**Comment by cyrilchapon** [comment]
It's not recommended for many reasons :

- [From PostgreSQL doc](https://www.postgresql.org/docs/9.1/sql-altertype.html)
  > ALTER TYPE ... ADD VALUE (the form that adds a new value to an enum type) cannot be executed inside a transaction block.
- [From PostgreSQL doc](https://www.postgresql.org/docs/9.1/sql-altertype.html)
  > Comparisons involving an added enum value will sometimes be slower than comparisons involving only original members of the enum type.

**Comment by abelosorio** [comment]
Hi @cyrilchapon, thanks for all your contributions. I'm out of work this week but I'll get back to this as soon as practicable.

**Comment by abelosorio** [comment]
OK, I'll close this. Transactions are a must for this package.
